### ISSUE TITLE
Put Data to list

### ISSUE THREAD

**Issue by fathialamre** [ashishrawat2911/network_handling#2]
How I cad put another data to list of movies

**Comment by ashishrawat2911** [comment]
Hi @fathialamre Can you explain it ?

**Comment by fathialamre** [comment]
Hi @ashishrawat2911 how to append new movies to data, using another event for example InsertEvent

`@override
  Stream<ResultState<List<Movie>>> mapEventToState(MovieEvent event) async* {

    yield ResultState.loading();

    if (event is LoadMovies) {

      ApiResult<List<Movie>> apiResult = await apiRepository.fetchMovieList();

      yield* apiResult.when(success: (List<Movie> data) async* {

        **_yield ResultState.data(data: data);_**

      }, failure: (NetworkExceptions error) async* {

        yield ResultState.error(error: error);

      });
    }
  }`

**Comment by ashishrawat2911** [comment]
List<Movie> movieList 

Make this on the top

Create a new event which will add another data to this existing list

movieList.add(NEWDATA)

**Comment by fathialamre** [comment]
Thanx @ashishrawat2911
