### ISSUE TITLE
Handle Validation Exception 422

### ISSUE THREAD

**Issue by fathialamre** [ashishrawat2911/network_handling#3]
How I can get vaidation errors from backend ?

**Comment by ashishrawat2911** [comment]
Hi @fathialamre 
Add new exception [here](https://github.com/ashishrawat2911/network_handling/blob/f98b4809a744e21c56b7677971f56e5dbe63acc1/lib/services/network_exceptions.dart#L42)

Now handle the exception [here](https://github.com/ashishrawat2911/network_handling/blob/f98b4809a744e21c56b7677971f56e5dbe63acc1/lib/services/network_exceptions.dart#L63) and in this [method](https://github.com/ashishrawat2911/network_handling/blob/f98b4809a744e21c56b7677971f56e5dbe63acc1/lib/services/network_exceptions.dart#L74)

**Comment by fathialamre** [comment]
Hi @ashishrawat2911
I tried above but not working, please explain it

Thanks

**Comment by AbdullahChauhan** [comment]
Hello @fathialamre 
Add the one more param "dynamic data" to this [func](https://github.com/ashishrawat2911/network_handling/blob/f98b4809a744e21c56b7677971f56e5dbe63acc1/lib/services/network_exceptions.dart#L44). Now pass this value  "error.response.data" to handleResponse func [here](https://github.com/ashishrawat2911/network_handling/blob/f98b4809a744e21c56b7677971f56e5dbe63acc1/lib/services/network_exceptions.dart#L94) so this assign to your first param. This way you can got the error data response inside this function specific to any status code!

**Comment by fathialamre** [comment]
> Hello @fathialamre
> Add the one more param "dynamic data" to this [func](https://github.com/ashishrawat2911/network_handling/blob/f98b4809a744e21c56b7677971f56e5dbe63acc1/lib/services/network_exceptions.dart#L44). Now pass this value "error.response.data" to handleResponse func [here](https://github.com/ashishrawat2911/network_handling/blob/f98b4809a744e21c56b7677971f56e5dbe63acc1/lib/services/network_exceptions.dart#L94) so this assign to your first param. This way you can got the error data response inside this function specific to any status code!

Thanks
